<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Aspire-A515-51G" name="JavaSusret21.Zadatak2" tests="2" failures="1" timestamp="2021-01-27T22:34:53 CET" time="28.135" errors="0">
  <testcase name="logIn" time="12.813" classname="JavaSusret21.Zadatak2">
    <failure type="java.lang.AssertionError" message="expected [wordpress_logged_in_4d8a854e0c8bd1c7f0585d2f4b3ad575=customer%7C1611861140%7CTidzpBAtN7vL46g7p2F7YFkB6A18FuNeNEpGVEBfPC3%7C5fbb658742b301d6f29951fdfc5c32c2d71c2624ce17c3cdd950ed9fdc202fb2; path=/] but found [wordpress_logged_in_4d8a854e0c8bd1c7f0585d2f4b3ad575=customer%7C1611956087%7CkcWtlMjOzEMPDOL9Gj4NttAvOHzS4bzkpbVA5VfGGBo%7C461f324bcf252d5bbb33e7815c65dea05c08e265e591d4ddc2577112daaa77be; path=/; domain=cms.demo.katalon.com]">
      <![CDATA[java.lang.AssertionError: expected [wordpress_logged_in_4d8a854e0c8bd1c7f0585d2f4b3ad575=customer%7C1611861140%7CTidzpBAtN7vL46g7p2F7YFkB6A18FuNeNEpGVEBfPC3%7C5fbb658742b301d6f29951fdfc5c32c2d71c2624ce17c3cdd950ed9fdc202fb2; path=/] but found [wordpress_logged_in_4d8a854e0c8bd1c7f0585d2f4b3ad575=customer%7C1611956087%7CkcWtlMjOzEMPDOL9Gj4NttAvOHzS4bzkpbVA5VfGGBo%7C461f324bcf252d5bbb33e7815c65dea05c08e265e591d4ddc2577112daaa77be; path=/; domain=cms.demo.katalon.com]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at JavaSusret21.Zadatak2.logIn(Zadatak2.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logIn -->
  <system-out/>
  <testcase name="dodavanjeItemaUKorpu" time="15.322" classname="JavaSusret21.Zadatak2"/>
  <system-out/>
</testsuite> <!-- JavaSusret21.Zadatak2 -->
